/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_efrenyang_ffmpeg_decoder_MainActivity */

#ifndef _Included_com_example_efrenyang_ffmpeg_decoder_MainActivity
#define _Included_com_example_efrenyang_ffmpeg_decoder_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_efrenyang_ffmpeg_decoder_MainActivity
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_efrenyang_ffmpeg_1decoder_MainActivity_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
