/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class com_example_efrenyang_helloworld_MainActivity */

#include "com_example_efrenyang_helloworld_MainActivity.h"
#ifdef __cplusplus
extern "C"{
#endif
#include "include/libavcodec/avcodec.h"
#include "include/libavformat/avformat.h"
#include "include/libavfilter/avfilter.h"

#ifdef ANDROID
#include <android/log.h>
#define LOGE(format, ...)  __android_log_print(ANDROID_LOG_ERROR, "(>_<)", format, ##__VA_ARGS__)
#else
#define LOGE(format, ...)  printf("(>_<) " format "\n", ##__VA_ARGS__)
#endif
/*
 * Class:     com_example_efrenyang_helloworld_MainActivity
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
 struct URLProtocol;
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_MainActivity_urlprotocolinfo(JNIEnv *env, jobject thiz)
  {
	char info[40960] = { 0 };

	av_register_all();

	struct URLProtocol *p_temp = NULL;
	avio_enum_protocols(&p_temp, 0);
	while (p_temp != NULL)
	{
		sprintf(info, "%s [In][%10s]\n", info, avio_enum_protocols(&p_temp, 0));
		//avio_enum_protocols(&p_temp, 0);
	}
	p_temp = NULL;
	avio_enum_protocols(&p_temp, 1);
	while (p_temp != NULL)
	{
		sprintf(info, "%s [Out][%10s]\n", info, avio_enum_protocols(&p_temp, 1));
		//avio_enum_protocols(&p_temp, 1);
	}
	LOGE("%s", info);
    return (*env)->NewStringUTF(env, info);
  }

/*
 * Class:     com_example_efrenyang_helloworld_MainActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_MainActivity_avformatinfo
  (JNIEnv *env, jobject thiz)
  {
  	char info[40960] = { 0 };

  	av_register_all();
  	struct AVInputFormat *i_temp = (struct AVInputFormat *)av_iformat_next(NULL);
  	struct AVOutputFormat *o_temp = (struct AVOutputFormat *)av_oformat_next(NULL);
  	while (i_temp != NULL)
  	{
  		sprintf(info, "%s [In][%10s]\n", info, i_temp->name);
  		i_temp = (struct AVInputFormat *)i_temp->next;
  	}
  	while (o_temp != NULL)
  	{
  		sprintf(info, "%s [Out][%10s]\n", info, o_temp->name);
  		o_temp = (struct AVOutputFormat *)o_temp->next;
  	}
  	LOGE("%s", info);
    return (*env)->NewStringUTF(env, info);
  }

/*
 * Class:     com_example_efrenyang_helloworld_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_MainActivity_avcodecinfo
  (JNIEnv *env, jobject thiz)
  {
  	char info[40960] = { 0 };

  	av_register_all();
  	struct AVCodec *c_temp = (struct AVCodec *)av_codec_next(NULL);

  	while (c_temp != NULL)
  	{
  		if (c_temp->decode != NULL)
  		{
  			sprintf(info, "%s[Dec]", info);
  		}
  		else
  		{
  			sprintf(info, "%s[Enc]", info);
  		}
  		switch (c_temp->type)
  		{
  		case AVMEDIA_TYPE_AUDIO:
  			sprintf(info, "%s[Audio]", info);
  			break;
  		case AVMEDIA_TYPE_VIDEO:
  			sprintf(info, "%s[Video]", info);
  			break;
  		default:
  			sprintf(info, "%s[Other]", info);
  			break;
  		}
  		sprintf(info, "%s[%10s]\n", info, c_temp->name);
  		c_temp = c_temp->next;
  	}
  	LOGE("%s", info);
    return (*env)->NewStringUTF(env, info);
  }

/*
 * Class:     com_example_efrenyang_helloworld_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_MainActivity_avfilterinfo
  (JNIEnv *env, jobject thiz)
  {
  	char info[40960] = { 0 };

  	av_register_all();

  	struct AVFilter	*f_temp = (struct AVFilter *)avfilter_next(NULL);

  	while (f_temp != NULL)
  	{
  		sprintf(info, "%s[%10s]", info, f_temp->name);
  		f_temp = (struct AVFilter *)f_temp->next;
  	}
  	LOGE("%s", info);
    return (*env)->NewStringUTF(env, info);
  }

/*
 * Class:     com_example_efrenyang_helloworld_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_MainActivity_configurationinfo
  (JNIEnv *env, jobject thiz)
  {
      char info[10000] = { 0 };
      char *temp;
      av_register_all();

      temp = avcodec_configuration();
      sprintf(info, "%s\n", temp);

      LOGE("%s", info);
      return (*env)->NewStringUTF(env, info);
  }

#ifdef __cplusplus
}
#endif
