/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_efrenyang_helloworld_Hellojni */

#ifndef _Included_com_example_efrenyang_helloworld_Hellojni
#define _Included_com_example_efrenyang_helloworld_Hellojni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_efrenyang_helloworld_Hellojni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_Hellojni_stringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_example_efrenyang_helloworld_Hellojni
 * Method:    unimplementedStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_Hellojni_unimplementedStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
