/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifdef __cplusplus
extern "C"{
#endif

#include "com_example_efrenyang_helloworld_Hellojni.h"
#include "include/libavcodec/avcodec.h"
/*
 * Class:     com_example_efrenyang_helloworld_Hellojni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_Hellojni_stringFromJni
        (JNIEnv *env, jobject thiz) {
#if defined(__arm__)
#if defined(__ARM_ARCH_8A__)
#if defined(__ARM_NEON__)
#define ABI "armeabi-v8a/NEON"
#else
#define ABI "armeabi-v8a"
#endif
#else
#define ABI "armeabi"
#endif
#elif defined(__i386__)
#define ABI "x86"
#elif defined(__mips__)
#define ABI "mips"
#else
#define ABI "unknown"
#endif
    return (*env)->NewStringUTF(env, "Hello from JNI !  Compiled with ABI " ABI ".");
}

/*
 * Class:     com_example_efrenyang_helloworld_Hellojni
 * Method:    unimplementedStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_efrenyang_helloworld_Hellojni_unimplementedStringFromJni
        (JNIEnv *env, jobject thiz) {
    char info[10000] = {0};
    sprintf(info, "%s\n", avcodec_configuration());
    return (*env)->NewStringUTF(env, info);
}

#ifdef __cplusplus
};
#endif

